// Build progress for this project, in the Master Website Build Checklist (v3.0).
// Items are referenced by their exact text in checklist/stages.json; the build script
// fails if a text does not match, so a mark can never silently point at nothing.
// Only items that were actually done and checked are marked. `na` = not relevant for this site.

export const project = {
  id: 'p-accountant-site',
  name: 'אתר תדמית — רואה חשבון / יועץ מס',
  data: {
    profile: 'corporate',
    projectKind: 'new',
    projectStatus: 'in-progress',
    siteName: 'אתר תדמית לרואה חשבון (תבנית)',
    client: 'רו״ח / יועץ מס — טרם נבחר (אתר הדגמה)',
    domain: '',
    owner: '',
    platform: 'Astro 7 — אתר סטטי',
    languages: 'עברית (RTL)',
    env: '',
    startDate: '2026-09-24',
    docVersion: '3.0',
    updatedDate: '2026-09-24',
    'track.client.status': 'in-progress',
    'track.research.status': 'in-progress',
    'track.arch.status': 'in-progress',
    'track.build.status': 'in-progress',
    'track.content.status': 'waiting-client',
    'track.onpage.status': 'in-progress',
    'track.tech.status': 'in-progress',
    'track.a11y.status': 'in-progress',
    'track.security.status': 'in-progress',
    'track.legal.status': 'in-progress',
    'track.conversion.status': 'in-progress',
    'stageNotes.client': 'שירותים, קהל יעד ומטרות לקוחים מהאיפיון. פרטי העסק עצמם הם נתוני הדגמה עד שייבחר לקוח.',
    'stageNotes.arch': 'כל פרטי העסק ב-src/data/business.ts; מדרגות מס, תקרות ומועדים ב-src/data/tax.ts; מחירים ב-src/data/pricing.ts. בדיקת scripts/check-single-source.mjs רצה לפני כל build ונכשלת אם נתון מוקלד ידנית מחוץ לקבצים האלה. נתון שחסר או שלא אומת מסומן בגלוי ("לאימות", באנר הדגמה, מקום לתמונה).',
    'stageNotes.content': 'התוכן הוא טיוטת הדגמה. נתוני המס 2026 נלקחו ממקורות משניים (מצוינים בעמוד) ומסומנים "לאימות" עד בדיקת איש מקצוע.',
    'stageNotes.a11y': 'axe-core (WCAG 2 A/AA) על כל 35 העמודים: 0 הפרות. טרם נבדק עם קורא מסך.',
    'stageNotes.tech': 'בדיקת קישורים על כל העמודים: 0 שבורים, 0 עמודים יתומים. Core Web Vitals ייבדקו על הסביבה החיה.',
    'stageNotes.conversion': 'הטופס שולח JSON ל-PUBLIC_FORM_ENDPOINT. עד שיוגדר יעד, הטופס מציג הודעת תקלה עם טלפון/WhatsApp (נבדק). GA4 נטען רק אחרי הסכמה ורק אם הוגדר PUBLIC_GA_ID.',
    'stageNotes.security': 'אתר סטטי ללא ממשק ניהול, ולכן סעיפי התחברות ו-2FA סומנו לא רלוונטיים לאתר עצמו (רלוונטיים לחשבונות האחסון והדומיין).',
  },
};

export const marks = {
  client: {
    done: [
      'קהל יעד הוגדר',
      'שירותים/מוצרים מרכזיים הוגדרו',
      'מטרת האתר הוגדרה',
      'שפות האתר הוגדרו (עברית בלבד או רב-לשוני)',
      'הוגדר אם זה אתר חדש או מעבר מאתר קיים (Migration)',
    ],
  },
  research: {
    done: ['שירותים/מוצרים מרכזיים מופו'],
  },
  arch: {
    done: [
      'Homepage מוגדרת',
      'עמוד לכל שירות/מוצר משמעותי',
      'About ו-Contact הוגדרו',
      'Blog/Knowledge Center הוגדר אם מתאים',
      'עמודי פרטיות, תנאי שימוש, נגישות ותקנון הוגדרו לפי הצורך',
      'הוחלט על מבנה URL עקבי (מומלץ באנגלית, לא בעברית)',
      'URL לכל עמוד הוגדר',
      'Internal linking ראשוני תוכנן',
      'CTA לכל עמוד מרכזי הוגדר',
      'רשימת העמודים הוזנה לטבלת מצב העמודים',
      'פרטי העסק (שם, טלפון, מייל, כתובת, שעות) מרוכזים במקום אחד ולא משוכפלים ידנית בין עמודים',
      'נתון שחסר מסומן בסימון גלוי במקום טקסט זמני, כדי שלא יישאר באוויר',
    ],
    na: ['מבנה שפות ו-hreflang תוכננו (אם רב-לשוני)'],
  },
  build: {
    done: [
      'העיצוב כולל נגישות מובנית: ניגודיות, גודל טקסט, מצבי Focus',
      'CMS, תבנית ותוספים הותקנו בגרסאות עדכניות',
      'הותקנו רק תוספים הכרחיים ומתוחזקים',
      'שפת הדף (lang) וכיוון הטקסט (dir) מוגדרים לעברית ו-RTL, ושפות נוספות בהתאם',
      'טקסט מעורב עברית/אנגלית, מספרים וטלפונים מוצגים נכון ב-RTL',
      'פונטים עבריים נבחרו עם רישיון מתאים',
      'פריסה רספונסיבית נבנתה לכל גדלי המסך',
      'הקוד מנוהל בגרסאות (Git) או מגובה באופן שוטף',
    ],
  },
  content: {
    done: [
      'המידע החשוב מופיע מוקדם',
      'FAQ נוסף רק כשיש ערך',
      'כל עמוד שירות/מוצר מציין במפורש מה, למי, איפה ובכמה, ומובן גם בלי הקשר חיצוני',
      'תאריך פרסום/עדכון מוצג בתוכן שבו זה רלוונטי',
      'לכל טענה עובדתית, מספר או נתון רגולטורי יש מקור, והמקור מצוין בעמוד',
    ],
    na: ['עמודי ערים או אזורים: לכל עמוד תוכן שלא ניתן להעתיק לעיר אחרת'],
  },
  onpage: {
    done: [
      'Title ייחודי',
      'Meta description ייחודי',
      'H1 ברור',
      'H2/H3 בהיררכיה הגיונית',
      'URL נקי',
      'Alt מתאים לתמונות',
      'Internal links קיימים',
      'Anchor text ברור',
      'Canonical מוגדר',
      'Open Graph ותמונת שיתוף מוגדרים',
      'Schema מתאים נבחר',
      'Organization/LocalBusiness/Article/Product/Service/Breadcrumb נבדקו לפי רלוונטיות',
      'Schema תואם למידע שמופיע בעמוד',
    ],
  },
  tech: {
    done: [
      'robots.txt הוגדר',
      'XML sitemap נוצר וכולל רק עמודים לאינדוקס',
      'עמוד 404 מותאם קיים ומחזיר קוד 404 אמיתי',
      'אין Broken links',
      'אין עמודים לא רצויים לאינדוקס',
      'פונטים: נטענים רק המשקלים הנדרשים, עם font-display: swap',
      'CSS/JS נבדקו: אין קוד מיותר שחוסם טעינה',
      'Lazy loading לתמונות מתחת לקפל (לא לתמונה הראשית)',
      'Favicon קיים',
      'אין עמודים יתומים: לכל עמוד באינדקס יש לפחות קישור פנימי אחד',
      'סט אייקונים מלא: favicon, apple-touch-icon ואייקוני 192/512',
      'פונטים מתארחים מקומית, והמשקל הקריטי נטען עם preload',
    ],
    na: ['hreflang הוגדר (אם רב-לשוני)'],
  },
  a11y: {
    done: [
      'מצב Focus נראה בבירור',
      'ניגודיות צבעים לפי WCAG AA (לפחות 4.5:1 לטקסט רגיל)',
      'תמונות דקורטיביות מוגדרות עם Alt ריק',
      'לכל שדה בטופס יש תווית (label), והודעות השגיאה ברורות',
      'לקישורים ולכפתורים יש טקסט מובן גם מחוץ להקשר',
      'בדיקה אוטומטית (Lighthouse / axe) ללא שגיאות קריטיות',
      'הצהרת נגישות פורסמה, כולל פרטי רכז נגישות ודרכי פנייה',
      'הנגישות לא נשענת על תוסף נגישות בלבד',
    ],
    na: ['לווידאו יש כתוביות, ואנימציות ניתנות לעצירה (אם רלוונטי)'],
  },
  security: {
    done: [
      'CMS, תבנית ותוספים מעודכנים',
      'תוספים ותבניות שלא בשימוש הוסרו',
      'הגנה מספאם בטפסים (Turnstile / reCAPTCHA / Honeypot)',
      'כותרות אבטחה הוגדרו (HSTS, X-Content-Type-Options, Referrer-Policy)',
    ],
    na: ['ניסיונות התחברות מוגבלים'],
  },
  legal: {
    done: [
      'מדיניות הפרטיות תואמת את המידע שהאתר אוסף בפועל (טפסים, Analytics, פיקסלים)',
      'הטפסים אוספים רק מידע נחוץ',
      'הסכמה לדיוור בתיבה נפרדת שאינה מסומנת מראש (חוק הספאם)',
      'באנר עוגיות ו-Consent Mode הוגדרו אם נדרש (למשל גולשים או פרסום באירופה)',
      'תנאי שימוש פורסמו לפי הצורך',
      'פרטי העסק המלאים מוצגים לפי הצורך (שם, ח.פ./ע.מ., כתובת, דרכי קשר)',
      'מחיר המוצג לצרכן הוא המחיר הכולל, כולל מע״מ',
    ],
  },
  conversion: {
    done: [
      'מטרת האתר ברורה מיד',
      'CTA ברור',
      'Key events מוגדרים: שליחת טופס, קליק לטלפון, קליק ל-WhatsApp',
      'פרמטרי UTM ומקור הפנייה נשמרים עם הליד',
      'כשל בשליחת טופס מוצג למשתמש ונרשם, ולא נעלם בשקט',
      'דף תודה בכתובת נפרדת, לשימוש כיעד המרה ב-Analytics ובפרסום',
      'סקריפטים של מדידה ופרסום נטענים רק אחרי הסכמת הגולש',
    ],
  },
  google: {
    done: [
      'שירותים/מוצרים מוגדרים מפורשות',
      'אין מידע סותר בין עמודים',
      'הוחלט אילו סורקי AI לאפשר ב-robots.txt (GPTBot, PerplexityBot, Google-Extended ועוד)',
    ],
  },
};
